services:
  jsoncrack:
    image: jsoncrack
    container_name: jsoncrack
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9090"
    environment:
      - NODE_ENV=production
